trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'VM deploy'
    subscriptionId: '4f1c4487-5965-44e4-b539-01b2e5d3994a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG_test'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gokuldxc/cicd/main/deploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/gokuldxc/cicd/main/deploymentParameters.json'
    deploymentMode: 'Incremental'